-- Migration: trip room V1.2 tables (owner-curated model)
-- Date: 2026-04-22 (amended 2026-04-16 for V1.2 per
--                  ~/.claude/plans/collaborative-trip-room-design.md
--                  § V1.2 — VOTING MODEL COLLAPSE + PARTICIPANT SCOPE LOCK)
-- Project: shared Supabase `bzmehrytiudgmgdrdlkg`
--
-- V1.2 scope:
--  - `trip_room_members`         — who joined the room (session-based, now
--                                  supports role='co-owner')
--  - `trip_room_slot_votes`      — the ONLY voting surface in V1.2; owner flags
--                                  a slot with 2+ items for group vote; one
--                                  row per (slot, session) upsert
--  - `trip_room_personal_items`  — each participant's own travel details
--                                  (arrival flight, departure flight, dietary
--                                  notes, etc.) — session_hash-owned
--  - `trip_bookings`             — handoff-kit click tracking (unchanged from V1)
--
-- DROPPED from V1 (nothing is in production yet, so we collapse the schema):
--  - trip_room_votes   — per-item thumbs was deleted in V1.2
--  - trip_room_flags   — per-item flags were deleted in V1.2
--
-- `trip_room_activity` already exists from 2026-04-16-signal-tables.sql;
-- reused here for join/slot-vote-open/vote/close/coowner-invite/claimed events.

-- ── Drop V1 tables if they were applied ──
-- Safe to run if the tables never existed. If someone did apply the original
-- V1 migration locally, this wipes their stale vote/flag rows cleanly.
DROP TABLE IF EXISTS trip_room_votes;
DROP TABLE IF EXISTS trip_room_flags;

-- ── members ──
-- role values now: 'owner' | 'co-owner' | 'participant' | 'viewer'
CREATE TABLE IF NOT EXISTS trip_room_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id TEXT NOT NULL,
  session_hash TEXT NOT NULL,
  display_name TEXT,
  email TEXT,
  role TEXT NOT NULL DEFAULT 'viewer',
  brand TEXT NOT NULL CHECK (brand IN ('moh', 'bestman', 'tdf')),
  notifications_opt_in BOOLEAN NOT NULL DEFAULT TRUE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_active_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (plan_id, session_hash)
);
CREATE INDEX IF NOT EXISTS idx_trip_room_members_plan ON trip_room_members (plan_id);
CREATE INDEX IF NOT EXISTS idx_trip_room_members_email ON trip_room_members (email) WHERE email IS NOT NULL;

-- ── slot votes (V1.2) ──
-- Participants vote on a specific slot that the owner flagged with 2+ items.
-- slot_id is generated by the owner (a uuid) and lives on
-- StoredPlan.voteSlots[].slotId in Redis.
-- chosen_item_path identifies which of the candidate items the voter picked,
-- e.g. "theLegend.dining.2". Changeable until the owner closes the vote.
CREATE TABLE IF NOT EXISTS trip_room_slot_votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id TEXT NOT NULL,
  slot_id TEXT NOT NULL,
  voter_session_hash TEXT NOT NULL,
  chosen_item_path TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (slot_id, voter_session_hash)
);
CREATE INDEX IF NOT EXISTS idx_trip_room_slot_votes_plan ON trip_room_slot_votes (plan_id);
CREATE INDEX IF NOT EXISTS idx_trip_room_slot_votes_slot ON trip_room_slot_votes (slot_id);

-- ── personal items (V1.2) ──
-- Each participant (including owner/co-owner) owns their travel-detail rows.
-- Reads are open (anyone in the room can see Sarah's flight). Writes are
-- enforced in the API route, not RLS — the route requires a matching
-- session_hash before allowing update/delete.
CREATE TABLE IF NOT EXISTS trip_room_personal_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id TEXT NOT NULL,
  participant_session_hash TEXT NOT NULL,
  participant_display_name TEXT,
  type TEXT NOT NULL CHECK (type IN (
    'arrival-flight', 'departure-flight',
    'arrival-time',   'departure-time',
    'dietary-note',   'custom'
  )),
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (plan_id, participant_session_hash, type)
);
CREATE INDEX IF NOT EXISTS idx_trip_room_personal_items_plan ON trip_room_personal_items (plan_id);
CREATE INDEX IF NOT EXISTS idx_trip_room_personal_items_session ON trip_room_personal_items (participant_session_hash);

-- ── trip_bookings (handoff-kit click tracking) ──
-- Logs each deep-link click for attribution even before partner postback arrives.
CREATE TABLE IF NOT EXISTS trip_bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id TEXT NOT NULL,
  item_path TEXT,
  partner TEXT NOT NULL,
  click_session_hash TEXT NOT NULL,
  deep_link_url TEXT NOT NULL,
  clicked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  converted_at TIMESTAMPTZ,
  converted_value_cents INT
);
CREATE INDEX IF NOT EXISTS idx_trip_bookings_plan ON trip_bookings (plan_id);
CREATE INDEX IF NOT EXISTS idx_trip_bookings_partner ON trip_bookings (partner, clicked_at DESC);
