/**
 * rank-expand-set.ts — Task 8: rank the deferred `expand` set into a human
 * greenlight list.
 *
 * Consumes `docs/expand-set.json` (Task 7's "relevant-but-not-yet-consumed"
 * reach) and aggregates it by (kind, targetWizard) into candidate engine
 * changes, ranked by leverage = rows × wizardsAffected. This is a REVIEW
 * artifact only — nothing here is wired into any engine. See
 * docs/expand-set-ranked.md for the rendered table and the effort heuristic
 * write-up.
 *
 * Run:  npx tsx scripts/rank-expand-set.ts        (writes docs/expand-set-ranked.md)
 * Test: npx tsx --test scripts/rank-expand-set.test.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import type { ExpandEntry } from "./backfill-tags";

export interface RankedCandidate {
  kind: string;
  targetWizard: string;
  candidate: string;
  rows: number;
  wizardsAffected: number;
  effort: "S" | "M" | "L";
  leverage: number;
}

/**
 * Effort heuristic — encoded per (kind, targetWizard) pair from a manual
 * read of src/tagging-rules.ts + src/oo-atlas.ts (Task 8, 2026-07-05):
 *
 *   S — the target wizard already has a working adapter for a structurally
 *       similar shared-array pattern (a site-keyed array carrying
 *       `sites`/`wizards` fields, e.g. `residencesForSite`) that this kind
 *       could be read through with a minor extension.
 *   M — the target wizard doesn't read this exact kind yet, but already
 *       reads an adjacent kind/category with an overlapping data shape
 *       (e.g. lodging-style venues) — needs a new reader, but one that
 *       follows an existing pattern.
 *   L — the target wizard has no reader touching this kind at all, and the
 *       kind is conceptually foreign to what it currently ingests (e.g. a
 *       party wizard reading golf-course data) — needs a net-new
 *       entity-kind reader plus new brand-fit logic.
 *
 * Any (kind, targetWizard) pair not explicitly analyzed falls back to "M" —
 * read as "needs a human look," not a confident estimate.
 */
const EFFORT_TABLE: Record<string, "S" | "M" | "L"> = {
  "golf-course|bestman": "L",
  "residence|bestman": "M",
  "residence|moh": "M",
  "golf-destination|offsite-retreat": "S",
  "golf-destination|offsite-outing": "S",
};

function estimateEffort(kind: string, targetWizard: string): "S" | "M" | "L" {
  return EFFORT_TABLE[`${kind}|${targetWizard}`] ?? "M";
}

/**
 * Pure aggregation + rank. Groups entries by (kind, targetWizard) for row
 * counts, and by kind alone for "wizards affected" — the number of distinct
 * target wizards that would benefit from the SAME entity-kind reader being
 * built, since that's the unit of engine-change effort. Sorted by
 * leverage = rows × wizardsAffected, descending (ties broken by rows, then
 * candidate name, for determinism).
 */
export function rankExpandSet(entries: ExpandEntry[]): RankedCandidate[] {
  const rowCounts = new Map<string, number>();
  const wizardsByKind = new Map<string, Set<string>>();

  for (const e of entries) {
    const pairKey = `${e.kind}|${e.targetWizard}`;
    rowCounts.set(pairKey, (rowCounts.get(pairKey) ?? 0) + 1);

    if (!wizardsByKind.has(e.kind)) wizardsByKind.set(e.kind, new Set());
    wizardsByKind.get(e.kind)!.add(e.targetWizard);
  }

  const candidates: RankedCandidate[] = [];
  for (const [pairKey, rows] of rowCounts) {
    const [kind, targetWizard] = pairKey.split("|");
    const wizardsAffected = wizardsByKind.get(kind)!.size;
    candidates.push({
      kind,
      targetWizard,
      candidate: `${kind} → ${targetWizard}`,
      rows,
      wizardsAffected,
      effort: estimateEffort(kind, targetWizard),
      leverage: rows * wizardsAffected,
    });
  }

  candidates.sort((a, b) => {
    if (b.leverage !== a.leverage) return b.leverage - a.leverage;
    if (b.rows !== a.rows) return b.rows - a.rows;
    return a.candidate.localeCompare(b.candidate);
  });

  return candidates;
}

function renderMarkdown(ranked: RankedCandidate[], totalEntries: number): string {
  const lines: string[] = [];
  lines.push("# Expand set — ranked engine-change greenlight list");
  lines.push("");
  lines.push(`Generated by \`scripts/rank-expand-set.ts\` on ${new Date().toISOString().slice(0, 10)}.`);
  lines.push("");
  lines.push(
    "This is the deferred engine-change greenlight list called for by the plan's " +
      "decision to do \"data + audit now, engine wiring later\" (Phase 2 close-out, " +
      "Task 8). It ranks the `expand` reach recorded in `docs/expand-set.json` " +
      "(Task 7) — rows that are relevant to a wizard but that no engine currently " +
      "reads. **Every row below is INERT.** Nothing here is live reach, and nothing " +
      "is wired into any wizard by this document. Wiring is a future, separate, " +
      "explicitly-greenlit task per candidate.",
  );
  lines.push("");
  lines.push(`Source: \`docs/expand-set.json\` — **${totalEntries}** total expand entries, aggregated below into ${ranked.length} candidates.`);
  lines.push("");
  lines.push("## Effort heuristic");
  lines.push("");
  lines.push("- **S** — the target wizard already has a working adapter for a structurally similar shared-array pattern (a site-keyed array carrying `sites`/`wizards` fields, e.g. `residencesForSite`) that this kind could be read through with a minor extension.");
  lines.push("- **M** — the target wizard doesn't read this exact kind yet, but already reads an adjacent kind/category with an overlapping data shape (e.g. lodging-style venues) — needs a new reader, but one that follows an existing pattern.");
  lines.push("- **L** — the target wizard has no reader touching this kind at all, and the kind is conceptually foreign to what it currently ingests (e.g. a party wizard reading golf-course data) — needs a net-new entity-kind reader plus new brand-fit logic.");
  lines.push("");
  lines.push("\"Wizards affected\" counts distinct target wizards for the same entity **kind** — the unit of engine-change effort is usually \"build a reader for this kind,\" and that reader can serve every wizard the kind expands to. Leverage = rows × wizards affected.");
  lines.push("");
  lines.push("## Ranked candidates");
  lines.push("");
  lines.push("| Rank | Candidate | Rows unlocked | Wizards affected | Effort | Leverage |");
  lines.push("|---:|---|---:|---:|:---:|---:|");
  ranked.forEach((c, i) => {
    lines.push(`| ${i + 1} | ${c.candidate} | ${c.rows} | ${c.wizardsAffected} | ${c.effort} | ${c.leverage} |`);
  });
  lines.push("");

  return lines.join("\n");
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const here = dirname(fileURLToPath(import.meta.url));
  const inputPath = join(here, "..", "docs", "expand-set.json");
  const outPath = join(here, "..", "docs", "expand-set-ranked.md");

  const raw = JSON.parse(readFileSync(inputPath, "utf-8")) as { total: number; entries: ExpandEntry[] };
  const ranked = rankExpandSet(raw.entries);
  writeFileSync(outPath, renderMarkdown(ranked, raw.total));

  console.log(`rank-expand-set: ${raw.entries.length} entries → ${ranked.length} candidates`);
  for (const c of ranked) {
    console.log(`  ${c.candidate}: rows=${c.rows} wizardsAffected=${c.wizardsAffected} effort=${c.effort} leverage=${c.leverage}`);
  }
  console.log(`wrote ${outPath}`);
}
