/**
 * Originally AUTO-GENERATED by plan-my-party/scripts/_extract-bm-locals.ts.
 * Since 2026-09-24 (CORPUS-M3a) the rows live in ./bestman-locals-data.ts and every
 * nested row that is a copy of a canonical row is stored as a REFERENCE to it;
 * the array below is derived at import (see src/locals-views.ts for the rules).
 * Do NOT re-run the extractor: it would write full copies back.
 * Best Man HQ's local bachelor-party destinations, extracted verbatim into the
 * shared universe and tagged sites:[bestman] wizards:[bestman] products:[bach-party].
 * Prose stays local (BM applyProseOverlay).
 */

export interface SharedBestmanLocal {
  id: string;
  city: string;
  state: string;
  region: string;
  wizards: string[];
  sites: string[];
  products: string[];
  [key: string]: unknown;
}

import { sharedDestinations } from "./destinations-canonical";
import { deriveLocals } from "./locals-views";
import { BESTMAN_LOCALS_SOURCE, BESTMAN_LOCALS_VIEW_ORDER } from "./bestman-locals-data";

export const SHARED_BESTMAN_LOCALS: SharedBestmanLocal[] = deriveLocals(
  BESTMAN_LOCALS_SOURCE,
  BESTMAN_LOCALS_VIEW_ORDER,
  sharedDestinations,
  "bestman-locals",
) as SharedBestmanLocal[];

export function bestmanLocals(): SharedBestmanLocal[] {
  return SHARED_BESTMAN_LOCALS;
}
