/**
 * Originally AUTO-GENERATED by tour-de-fore/scripts/_extract-golf-destinations.ts.
 * The 234 golf-trip destinations (courses/lodging/dining/bars/activities/
 * partyBuses/privateChefs embedded), extracted verbatim into the shared universe.
 *
 * These are HANDICAP HQ's destinations. The name is historical: they were
 * extracted from Tour de Fore before the 2026-07-02 split moved the golf-trip
 * wizard to handicaphq.com. `wizards` was migrated `["tdf"] → ["handicap"]` on
 * 2026-07-31 when the tdf wizard was retired — the rows had been routed to a
 * consumer that no longer exists, and only reached HHQ because HHQ imports the
 * array directly and never filters on tags.
 *
 * Tagged sites:[handicap] wizards:[handicap] products:[golf-trip].
 * Prose stays local (HHQ applyProseOverlay).
 *
 * DO NOT hand-edit the data rows — regenerate. The re-extraction script lives in
 * the tour-de-fore repo and predates the split; if these are ever regenerated,
 * the generator must emit wizards:["handicap"] AND emit each embedded course as
 * a reference to golf-courses.ts (CORPUS-M3a) — a full copy would silently
 * fork the course again.
 *
 * The rows themselves live in ./golf-destinations-data.ts since 2026-09-24.
 */

import { GOLF_COURSE_INDEX, SHARED_GOLF_COURSES_HHQ_MERGE } from "./golf";
import type { SharedGolfCourse } from "./golf-courses";
import { GOLF_DESTINATIONS_SOURCE, GOLF_EMBEDDED_COURSE_ORDER } from "./golf-destinations-data";
import { deriveRow, isRowRef, resolveRef } from "./row-views";
import { stripUnpublishableImageUrls } from "./image-url-hygiene";

export interface SharedGolfDestination {
  id: string;
  city: string;
  state: string;
  region: string;
  sites: string[];
  wizards: string[];
  products: string[];
  [key: string]: unknown;
}

/**
 * The 234 destinations as consumers read them, every embedded course DERIVED
 * from its canonical record (CORPUS-M3a). The source file stores each embedded
 * course as a reference, `{"ref": "<course id>"}`: the 994 embedded copies
 * matched the flat catalog 1:1 with 0 conflicting values, so there was nothing
 * to keep per copy except, for 4 rows, the original key order. A reference
 * that resolves to no course THROWS here, at import — see src/row-views.ts.
 */
export const SHARED_GOLF_DESTINATIONS: SharedGolfDestination[] = GOLF_DESTINATIONS_SOURCE.map((d) => {
  const courses = d.courses;
  if (!Array.isArray(courses)) return d as unknown as SharedGolfDestination;
  return {
    ...d,
    courses: courses.map((c) =>
      isRowRef(c)
        ? deriveRow(c, resolveRef(GOLF_COURSE_INDEX, c.ref, `golf destination ${d.id}`), GOLF_EMBEDDED_COURSE_ORDER)
        : c,
    ),
  } as unknown as SharedGolfDestination;
});

/**
 * Shape of an embedded destination course, as Handicap HQ's pages read it.
 * `holes`/`par`/`yardage` are OPTIONAL here on purpose: they are substantive
 * published facts, and a researched row that doesn't carry them must render
 * without them rather than have them invented (see the honesty firewall in
 * `scripts/ingest-researched.ts`). HHQ omits the stat when it's absent.
 */
export interface EmbeddedCourse {
  name: string;
  tier: string;
  greenFeeRange: [number, number];
  style: string;
  walkable: boolean;
  driveMinutes: number;
  highlight: string;
  holes?: number;
  par?: number;
  yardage?: number;
  url?: string;
  googleRating?: number;
  reviewCount?: number;
  hypeTag?: string;
  rankNote?: string;
  [key: string]: unknown;
}

/** Project a flat catalog course into the embedded-course shape. Copies only
 *  fields the row actually has — never fabricates a stat to fill the shape. */
function toEmbeddedCourse(c: SharedGolfCourse): EmbeddedCourse {
  const out: EmbeddedCourse = {
    ...(c.id !== undefined ? { id: c.id } : {}),
    name: c.name,
    tier: c.tier,
    greenFeeRange: c.greenFeeRange,
    style: c.style,
    walkable: c.walkable,
    driveMinutes: c.driveMinutes,
    highlight: c.highlight,
  };
  if (c.url !== undefined) out.url = c.url;
  if (c.googleRating !== undefined) out.googleRating = c.googleRating;
  if (c.reviewCount !== undefined) out.reviewCount = c.reviewCount;
  if (c.hypeTag !== undefined) out.hypeTag = c.hypeTag;
  if (c.rankNote !== undefined) out.rankNote = c.rankNote;
  return out;
}

/**
 * The golf-trip destinations, with any sanctioned-ingest course that names a
 * `destinationId` ATTACHED to that destination's `courses[]`.
 *
 * Why this exists (2026-07-31): researched golf rows landed in the flat
 * catalog only, and Handicap HQ renders courses from the destination-embedded
 * `courses[]` — so a researched course closed an audit gap and then appeared on
 * no page. 38 of 999 catalog courses had no destination to live in. Attaching
 * here means a researched course inherits `/golf-trips/[slug]/courses/[course]`,
 * which already exists, instead of needing a new surface.
 *
 * Attach is by EXPLICIT `destinationId`, never by guessing from city/state —
 * the geography is international and string-matching towns across countries is
 * exactly the kind of silent mis-association this repo keeps getting bitten by.
 * Dedup is by course name (case-insensitive): a course already embedded in the
 * destination wins, so re-ingesting can't double it.
 */
export function golfDestinations(): SharedGolfDestination[] {
  const byDestination = new Map<string, SharedGolfCourse[]>();
  for (const c of SHARED_GOLF_COURSES_HHQ_MERGE) {
    if (!c.destinationId) continue;
    const list = byDestination.get(c.destinationId);
    if (list) list.push(c);
    else byDestination.set(c.destinationId, [c]);
  }
  const merged =
    byDestination.size === 0
      ? SHARED_GOLF_DESTINATIONS
      : SHARED_GOLF_DESTINATIONS.map((dest) => {
          const extra = byDestination.get(dest.id);
          if (!extra) return dest;
          const existing = (dest.courses as EmbeddedCourse[] | undefined) ?? [];
          const seen = new Set(existing.map((c) => c.name.trim().toLowerCase()));
          const additions = extra
            .filter((c) => !seen.has(c.name.trim().toLowerCase()))
            .map(toEmbeddedCourse);
          if (additions.length === 0) return dest;
          return { ...dest, courses: [...existing, ...additions] };
        });

  // TWO independent strips, on disjoint fields, both applied last so they cover
  // the sanctioned-ingest courses attached above and not just the generated rows.
  // They arrived as a merge conflict because each added the same `merged` hoist
  // to hang itself off; they are not alternatives and dropping either restores a
  // bug that reached users.
  //   stripUnprovenancedVenueUrls — non-course venue `url`s with no provenance
  //     (the 91 name-slugged domains: hash-kitchen.com is a construction company)
  //   stripUnpublishableImageUrls — course `imageUrl`s that are tracking beacons
  //     (xad.com and facebook.com/tr pixels firing on every render)
  return stripUnpublishableImageUrls(merged.map(stripUnprovenancedVenueUrls));
}

/**
 * Venue arrays whose `url` is not trustworthy on its own. `courses` is
 * deliberately NOT in this list — see the note on the strip below.
 */
const UNVERIFIED_URL_ARRAYS = [
  "dining",
  "bars",
  "activities",
  "lodging",
  "partyBuses",
  "privateChefs",
] as const;

/** The provenance the backfill actually writes (`research-schema.ts`): a source
 *  URL the value was read FROM, plus at least one citation. */
function hasRealProvenance(row: Record<string, unknown>): boolean {
  const cites = row.citations;
  return (
    typeof row.sourceUrl === "string" &&
    row.sourceUrl.trim() !== "" &&
    Array.isArray(cites) &&
    cites.length > 0
  );
}

/**
 * Drop `url` from non-course golf venues that carry no provenance.
 *
 * These 91 URLs were not researched — they are the venue's own name slugged
 * into a domain, and they are WRONG. Measured 2026-08-05: 90 of 91 are a bare
 * host with no path and 89 of 91 are a mechanical slug of the name. Resolving
 * them shows what they actually are: `hash-kitchen.com` is a construction
 * company, `the-shed.com` is an artist's blog, `geronimo.com` is a nonprofit
 * consultancy. Where a venue appears in BOTH the party and golf datasets, the
 * two disagree every time and the party value is the correct one.
 *
 * They survived every gate because they all return HTTP 200, and `verify-url`
 * asks whether a URL is alive, not whether it is the right place. A 200 is not
 * proof of subject. Until a check exists that can tell those apart, presence in
 * this dataset cannot confer trust.
 *
 * Stripping rather than blanking: downstream treats a non-blank `url` as
 * provenance (`backfill-queue.ts` counts a row as sourced iff `url` is
 * non-blank), so leaving the key behind would keep these scored as sourced and
 * keep them out of the backfill queue that should now pick them up.
 *
 * Forward-compatible by construction: a row that DOES carry `sourceUrl` +
 * `citations` keeps its URL, so when the golf backfill lands real provenance
 * these rows go clickable again with no further change here. Today zero golf
 * rows qualify — those fields do not yet exist in this dataset at all.
 *
 * Courses are left alone on purpose. They are 88% covered with mostly real
 * hosts and deep paths (`tpc.com/scottsdale`), only ~11% match the fabrication
 * fingerprint, and HHQ gates the remainder on render (handicap-hq#24). Note
 * that 88% is COVERAGE, not verification — nothing here attests a course URL
 * was ever checked.
 */
function stripUnprovenancedVenueUrls(dest: SharedGolfDestination): SharedGolfDestination {
  let changed = false;
  const out: Record<string, unknown> = { ...dest };

  for (const key of UNVERIFIED_URL_ARRAYS) {
    const arr = dest[key];
    if (!Array.isArray(arr)) continue;

    let arrChanged = false;
    const next = arr.map((v) => {
      if (!v || typeof v !== "object" || Array.isArray(v)) return v;
      const row = v as Record<string, unknown>;
      if (typeof row.url !== "string" || row.url.trim() === "") return v;
      if (hasRealProvenance(row)) return v;
      arrChanged = true;
      const { url: _unverified, ...rest } = row;
      return rest;
    });

    if (arrChanged) {
      out[key] = next;
      changed = true;
    }
  }

  return changed ? (out as SharedGolfDestination) : dest;
}
