/**
 * Originally AUTO-GENERATED by maid-of-honor-hq/scripts/_extract-moh-locals.ts.
 * Since 2026-09-24 (CORPUS-M3a) the rows live in ./moh-locals-data.ts and every
 * nested row that is a copy of a canonical row is stored as a REFERENCE to it;
 * the array below is derived at import (see src/locals-views.ts for the rules).
 * Do NOT re-run the extractor: it would write full copies back.
 * MOH's local bachelorette destinations, extracted verbatim into the shared
 * universe and tagged sites:[moh] wizards:[moh] products:[bachelorette].
 * Prose stays local (MOH applyProseOverlay + applyEnrichmentOverlay).
 */

export interface SharedMohLocal {
  id: string;
  city: string;
  state: string;
  region: string;
  wizards: string[];
  sites: string[];
  products: string[];
  [key: string]: unknown;
}

import { sharedDestinations } from "./destinations-canonical";
import { deriveLocals } from "./locals-views";
import { MOH_LOCALS_SOURCE, MOH_LOCALS_VIEW_ORDER } from "./moh-locals-data";

export const SHARED_MOH_LOCALS: SharedMohLocal[] = deriveLocals(
  MOH_LOCALS_SOURCE,
  MOH_LOCALS_VIEW_ORDER,
  sharedDestinations,
  "moh-locals",
) as SharedMohLocal[];

export function mohLocals(): SharedMohLocal[] {
  return SHARED_MOH_LOCALS;
}
